"""Alerts page: risk alert monitoring, health scores and alert history."""
import pandas as pd
import streamlit as st

import shared
from api_client import APIError
from shared import live_ticker, run_check_now


def render(ctx) -> None:
    client = ctx.client
    selected_user_id = ctx.selected_user_id

    live_ticker(client)
    st.markdown("**Risk alerts**", unsafe_allow_html=True)
    st.caption(
        "Alerts are generated by the backend's risk rules (volatility, drawdown, VaR, "
        "Sharpe, beta) and portfolio health score."
    )

    email_alerts = st.checkbox(
        "Email me the alert summary",
        value=False,
        help="Emails the generated alerts to the user's registered address "
        "(requires SMTP credentials on the backend).",
    )
    if st.button("Run alert check now", type="primary", width="stretch"):
        result = run_check_now(client, selected_user_id, send_email=email_alerts)
        if result is not None:
            st.success(
                f"Checked {result['portfolios_checked']} portfolio(s) — "
                f"{result['alerts_created']} new alert(s)."
            )
            if email_alerts:
                if result.get("emailed") and result.get("emails_sent"):
                    st.success("Alert summary emailed to your registered address.")
                else:
                    st.warning(
                        "No email sent — either SMTP is not configured on the "
                        "backend or there were no abnormal alerts to email."
                    )
            st.rerun()

    try:
        payload = client.list_alerts(selected_user_id, unread_only=False, limit=500)
    except APIError as exc:
        st.error(f"Could not load alerts: {exc}")
        payload = {}

    all_alerts = payload.get("alerts") or []
    unread_count = int(payload.get("unread_count") or 0)

    st.markdown("**Unread alerts summary**", unsafe_allow_html=True)
    st.write(f"{unread_count} unread alert(s)")

    if unread_count:
        newest = next((a for a in all_alerts if not a.get("is_read")), None) or (all_alerts[0] if all_alerts else {})
        st.warning(f"{unread_count} unread risk alert(s) — {newest.get('message', '')}")
    else:
        st.success("No unread risk alerts — all clear.")

    st.markdown("**Alert history**", unsafe_allow_html=True)
    unread_only = st.checkbox("Unread only", value=False)
    filtered = [a for a in all_alerts if not unread_only or not a.get("is_read")]

    if not filtered:
        st.info("No alerts" + (" (unread)" if unread_only else "") + ".")
    else:
        unread_rows = [a for a in filtered if not a.get("is_read")]
        if unread_rows:
            ids = {a["alert_id"]: a["message"] for a in unread_rows}
            selected = st.multiselect(
                "Mark as read",
                options=list(ids.keys()),
                format_func=lambda i: f"#{i} · {ids[i][:70]}",
            )
            if selected and st.button("Mark selected as read"):
                for alert_id in selected:
                    try:
                        client.mark_alert_read(alert_id)
                    except APIError:
                        pass
                st.rerun()

        rows = [
            {
                "ID": a["alert_id"],
                "Severity": str(a.get("severity", "")).title(),
                "Category": a.get("category", "").title(),
                "Metric": a.get("metric", ""),
                "Message": a.get("message", ""),
                "Portfolio": a.get("portfolio_id", "—"),
                "Status": "Unread" if not a.get("is_read") else "Read",
                "Created": str(a.get("created_at", ""))[:19],
            }
            for a in filtered
        ]
        st.dataframe(pd.DataFrame(rows), width="stretch", hide_index=True)
        st.caption(f"{len(filtered)} alert(s) shown.")


def main() -> None:
    """Streamlit page entrypoint."""
    ctx = shared.require_context()
    render(ctx)
